import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb5a0",
        "on-surface": "#191c1e",
        "inverse-surface": "#2e3132",
        "on-secondary": "#ffffff",
        "primary-fixed": "#e2e2e5",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fb",
        "on-error": "#ffffff",
        "secondary": "#944933",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#f0f1f3",
        "on-tertiary-fixed-variant": "#394b3d",
        "tertiary-fixed-dim": "#b7ccb9",
        "surface-container": "#edeef0",
        "on-secondary-fixed-variant": "#76321e",
        "tertiary-container": "#0e1f13",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffdbd1",
        "background": "#f8f9fb",
        "on-tertiary": "#ffffff",
        "primary-container": "#1a1c1e",
        "on-secondary-fixed": "#3b0900",
        "primary-fixed-dim": "#c6c6c9",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1a1c1e",
        "on-background": "#191c1e",
        "outline": "#75777a",
        "surface-variant": "#e1e2e4",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#0e1f13",
        "surface": "#f8f9fb",
        "primary": "#000101",
        "surface-container-high": "#e7e8ea",
        "secondary-container": "#ffa086",
        "surface-tint": "#5d5e61",
        "surface-container-highest": "#e1e2e4",
        "on-surface-variant": "#44474a",
        "tertiary": "#000000",
        "on-primary-container": "#838486",
        "tertiary-fixed": "#d3e8d5",
        "on-secondary-container": "#793521",
        "on-tertiary-container": "#758978",
        "surface-dim": "#d9dadc",
        "on-primary-fixed-variant": "#454749",
        "outline-variant": "#c5c6ca",
        "inverse-primary": "#c6c6c9"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-tablet": "32px",
        "container-max": "1440px",
        "unit": "8px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-outfit)", "sans-serif"],
        "display-lg": ["var(--font-outfit)", "sans-serif"],
        "data-tabular": ["var(--font-jetbrains)", "monospace"],
        "body-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-caps": ["var(--font-plus-jakarta)", "sans-serif"],
        "kpi-metric": ["var(--font-outfit)", "sans-serif"],
        "headline-lg": ["var(--font-outfit)", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta)", "sans-serif"],
      },
      fontSize: {
        "display-lg":        ["2.25rem",  { lineHeight: "2.75rem", letterSpacing: "-0.02em" }],
        "headline-lg":       ["1.5rem",   { lineHeight: "2rem",    letterSpacing: "-0.01em" }],
        "headline-lg-mobile":["1.25rem",  { lineHeight: "1.75rem", letterSpacing: "-0.01em" }],
        "kpi-metric":        ["2rem",     { lineHeight: "2.5rem",  letterSpacing: "-0.02em" }],
        "body-md":           ["0.9375rem",{ lineHeight: "1.5rem",  letterSpacing: "0" }],
        "label-md":          ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0" }],
        "label-caps":        ["0.6875rem",{ lineHeight: "1rem",    letterSpacing: "0.06em" }],
        "data-tabular":      ["0.8125rem",{ lineHeight: "1.25rem", letterSpacing: "0" }],
      },
    },
  },
  plugins: [],
};
export default config;
